# Generated by Django 5.2.8 on 2025-11-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('date', 'Termin'), ('location', 'Lokalizacja')], default='date', max_length=20),
        ),
    ]
